config/routes.rb
Rails.application.routes.draw do
  patch 'items/pick/:id', to: "items#pick", as: :pick

  devise_for :users
  root to: 'lists#index'
  resources :lists do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  belongs_to :user, optional: true
  before_save :smart_add_url_protocol
  validates :item_name, presence: true
  validates :description, presence: true

  protected

  def smart_add_url_protocol
    unless link[/\Ahttp:\/\//] || link[/\Ahttps:\/\//]
      self.link = "http://#{link}"
    end
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :items

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :create_user_list

  has_many :lists
  has_many :items, through: :lists

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def create_user_list
    List.create(owner: self.first_name, title: "#{self.first_name}'s list", user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :password])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
  end

  def create
    @list = List.find(params[:list])
    @item = Item.new(item_params)
    @item.list_id = @list.id
    @item.user_id = current_user.id
    if @item.save!
      redirect_to list_path(@list), notice: "Item added to list."
    else
      render :new, notice: "Something went wrong..."
    end
  end

  def edit
    @list = List.find_by_id(params[:list_id])
    @item = Item.find_by_id(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def show
    @item = Item.find_by_id(param[:id])
  end

  def update
    @item = Item.find(params[:id])
    @list = List.find(params[:list_id])
    if @item.update(item_params)
      redirect_to list_path(@list), notice: "Item updated."
    else
      render :new, notice: "Something went wrong..."
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to list_path(params[:list_id]), notice: "Item deleted..."
  end

  def pick
    item = Item.find(params[:id])
    if item.buyer.nil?
      item.buyer = current_user.id
    else
      item.buyer = nil
    end
    item.save!
    redirect_to lists_path
  end

  private

  # PARAMS

  def item_params
    params.require(:item).permit(:item_name, :description, :link, :price)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.js.erb
$("#updateModal").html("<%= escape_javascript(render partial: 'items/partial/update_item') %>");

// document.querySelector('#update-form').insertAdjacentHTML('afterbegin', "<%= escape_javascript(render partial: 'items/partial/update_item') %>" );

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/partial/_add_item.html.erb
<a type="" class="btn btn-outline-primary" data-toggle="modal" data-target="#addModal">
  Add item
</a>

<!-- Modal -->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add item</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@list, Item.new], remote: true do |f| %>
            <%= hidden_field_tag 'list', @list.id %>
            <%= f.input :item_name %>
            <%= f.input :description %>
            <%= f.input :link %>
            <%= f.input :price %>
            <%= f.submit "Add Item", class: "btn btn-outline-primary" %>
      <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-warning" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/items/partial/_update_item.html.erb
<!-- Modal -->
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-dialog">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Update Item</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <%= simple_form_for [@list, @item], remote: true do |f| %>
            <%= hidden_field_tag 'list', @list.id %>
            <%= f.input :item_name, input_html: {value: @item.item_name } %>
            <%= f.input :description, input_html: {value: @item.description } %>
            <%= f.input :link, input_html: {value: @item.link } %>
            <%= f.input :price, input_html: {value: @item.price } %>
            <%= f.submit "Update Item", class: "btn btn-outline-primary" %>
      <% end %>

        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-warning" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>

app/views/items/pick.html.erb
<h1>Items#pick</h1>
<p>Find me in app/views/items/pick.html.erb</p>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Listy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/caef749058.js" crossorigin="anonymous"></script>
    <%= favicon_link_tag asset_path('listy.png') %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/nav_shaddow' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-5">
      <h2>Hello <%= current_user.first_name %> 👋</h2>
      <p>Welcome to Listy, the new home of your gift lists</p>
      <h4 class="mb-3">Manage: <%= link_to "Your list", list_path(current_user.lists.ids) %></h4>
      <p><strong>Key:</strong> Available <i class="far fa-circle green pr-1"></i> Selected: <i class="fas fa-check-circle green pr-1"></i>  Unavailable: <i class="fas fa-circle gray pr-1"></i></p>
      <% @lists.each do |list| %>
        <% next if list.user == current_user %>
      <% @list = list%>
        <div class="card p-3 mb-3">
          <p><%= list.title %> ID: <%= list.id  %> </p>
            <% list.items.sort.each do |item| %>
            <div class="list-flex">
              <div class="item_name"><%= item.item_name %></div>
              <div class="description"><%= item.description %></div>
              <div class="w-12">£<%= item.price %></div>
              <div class="w-10 text-center"><a href="<%= item.link %>" target="_blank">Link</a></div>
              <div class="w-10 text-center">
              <% if item.buyer.nil? %>
              <%= link_to pick_path(item), method: :patch, remote: true do %><i class="far fa-circle green"></i><% end %>
              <% elsif item.buyer == current_user.id %>
              <%= link_to pick_path(item), method: :patch, remote: true do %><i class="fas fa-check-circle green"></i><% end %>
              <% else %>
              <i class="fas fa-circle gray"></i>
              <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

app/views/lists/partial/_add_item.html.erb
<a type="" class="btn btn-outline-primary" data-toggle="modal" data-target="#addModal">
  Add item
</a>

<!-- Modal -->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add item</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@list, Item.new], remote: true do |f| %>
            <%= hidden_field_tag 'list', @list.id %>
            <%= f.input :item_name%>
            <%= f.input :description%>
            <%= f.input :link%>
            <%= f.input :price %>
            <%= f.submit "Add Item", class: "btn btn-outline-primary" %>
      <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-warning" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-5">
      <h2>Hello <%= current_user.first_name %> 👋</h2>
      <p>Welcome to Listy, the new home of your gift lists</p>
      <h4 class="mb-3">Manage: <%= link_to "Family lists", lists_path %></h4>


        <div class="card p-3 mb-3">
            <p><%= @list.title %> ID: <%= @list.id  %> </p>
            <% @list.items.sort.each do |item| %>
              <div class="list-flex">
                <div class="item_name"><%= item.item_name %></div>
                <div class="description m-w-60"><%= item.description %></div>
                <div class="w-12">£<%= item.price %></div>
                <div class="w-10 text-center"><a href="<%= item.link %>" target="_blank">Link</a></div>

                <div class="w-10 text-center" ><%= link_to edit_list_item_path(@list, item), data: {toggle: 'modal', target: '#updateModal'}, remote: true do %><i class="fas fa-edit"></i><% end %></div>

                <div class="w-10 text-center"><%= link_to list_item_path(@list, item), class: 'red', method: :delete, data: { confirm: 'Are you sure that you want to delete this item?' }, remote: true do %><i class="fas fa-times"></i><% end %></div>
              </div>
            <% end %>
        </div>

      <%= render "items/partial/add_item" %>

    </div>
  </div>
</div>


<!-- Fade class stopping modal from closing  -->
<div class="modal" id="updateModal"  aria-labelledby="exampleModalLabel" aria-hidden="true"></div>

app/views/lists/update.html.erb
<h1>Lists#update</h1>
<p>Find me in app/views/lists/update.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Welcome to Listy!</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_nav_shaddow.html.erb
<div class="w-100 shaddow" style="height: 2px;"></div>

app/views/shared/_navbar.html.erb
<!-- <div class="nav-wrapper shaddow">
    <div class="container p-0"> -->
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon container">
      <%= link_to "#", class: "navbar-brand" do %>
        <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
        <% end %>
        <h2 class="bold text-left">Listy</h2>



      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
            <li class="nav-item ">
              <%= link_to "Home", "#", class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link"  %>
            </li>

          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
<!--   </div>
</div> -->